const ERROR_INCORRECT = 400;
const ERROR_INVALID_TOKEN = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_UNFIND = 404;
const ERROR_UNUNIQUE = 409;
const ERROR_DEFAULT = 500;

module.exports = {
  ERROR_INCORRECT,
  ERROR_INVALID_TOKEN,
  ERROR_FORBIDDEN,
  ERROR_UNFIND,
  ERROR_UNUNIQUE,
  ERROR_DEFAULT,
};
